### ISSUE TITLE
Always capture stdout

### ISSUE THREAD

**Issue by atilante** [apluslms/python-grader-utils#5]
Capturing stdout (output of print() commands in student solutions) should be always captured and displayed inside HTML "pre" tags in separate box, when the result is shown in A+ to the student. Example: exercise "palindromi" on course "Tietotekniikka sovelluksissa".

**Comment by Mankro** [comment]
In this new pull request https://github.com/apluslms/python-grader-utils/pull/18, the stdout is captured and thrown away. There used to be a bug that the grader utils crashed if the student printed anything to stdout and the final feedback was then completely empty. That bug has been fixed. However, this issue also requests that the student's prints could be displayed as part of the final feedback. @atilante Is that an important requirement? There are reasons to hide all the student's prints since they could be used to collect information from the grader in order to cheat in the automatic grading.

**Comment by atilante** [comment]
Great to see that bugfix! I think there's no need to have an option that would still make Graderutils record student's prints to stdout. I tested the aforementioned Palindrome exercise with the latest Graderutils. The unit tests of that exercise use `@patch("sys.stdout", new_callable=io.StringIO)` to examine the output of the student's program, and that works fine. I think we can close this issue.
